### ISSUE TITLE
issue：the extension does not work when vscode work in 'Remote -SSH ' mode

### ISSUE THREAD

**Issue by zhweiGuo** [CoenraadS/Bracket-Pair-Colorizer-2#187]
vscode info:
```
Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```
remote machine: Ubuntu 18.04

**Comment by tats-u** [comment]
I have a similar issue.
Code says "Extension is enabled locally and disabled on 'SSH: `*snip*`", but I can't enable the extension in the remote machine.

Remote OS: Ubuntu 18.04

**Comment by verdimrc** [comment]
I forced this extension to run remotely, and the output indicated failure to find vscode-textmate on the remote server.

```
[2020-01-05 18:15:42.979] [exthost] [error] Activating extension CoenraadS.bracket-pair-colorizer-2 failed due to an error:
[2020-01-05 18:15:42.981] [exthost] [error] Error: Cannot find module '/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/node_modules.asar/vscode-textmate'
Require stack:
- /home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/textMateLoader.js
- /home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/settings.js
- /home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecorationManager.js
- /home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/extension.js
- /home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/loader.js
- /home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/bootstrap-amd.js
- /home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
	at Function.Module._load (internal/modules/cjs/loader.js:527:27)
	at Function.t._load (/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:844:268)
	at Function.n._load (/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:814:264)
	at Function.i._load (/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:810:704)
	at Module.require (internal/modules/cjs/loader.js:681:19)
	at require (internal/modules/cjs/helpers.js:16:16)
	at TextMateLoader.getNodeModule (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/textMateLoader.js:98:16)
	at TextMateLoader.loadTextMate (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/textMateLoader.js:101:21)
	at new TextMateLoader (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/textMateLoader.js:18:27)
	at new Settings (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/settings.js:10:31)
	at new DocumentDecorationManager (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/documentDecorationManager.js:9:25)
	at activate (/home/ec2-user/.vscode-server-insiders/extensions/coenraads.bracket-pair-colorizer-2-0.0.29/out/src/extension.js:6:37)
	at Function._callActivateOptional (/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:720:141)
	at Function._callActivate (/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:719:810)
	at /home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/out/vs/server/remoteExtensionHostProcess.js:718:960
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
	at async Promise.all (index 6)
```

I further experimented with installing vscode-textmate on `/home/ec2-user/node_modules/`, then symlinked it as `/home/ec2-user/.vscode-server-insiders/bin/7c0095ee2d064033fc13184127a9adc603454729/node_modules.asar/`. This will remove the above error message, but still no bracket colorizations.

**Comment by Stanzilla** [comment]
Same here, @CoenraadS any chance you could fix this?

**Comment by egamma** [comment]
This extension must run as 'ui' extension and VS Code has configured it like this.

**Comment by ShuhuaGao** [comment]
Still have the same issue with v0.2.0 on remote-SSH.

**Comment by CoenraadS** [comment]
I will accept a PR for this

**Comment by egamma** [comment]
@CoenraadS we (the code team) are also interested in this support. We will start to look into this in one of the next iterations. However, it is not fully clear yet that this can be fully achieved in a PR and might need some additional support from the VS Code core.
