### ISSUE TITLE
Runtime Error stating: "Must invoke loadWASM first"

### ISSUE THREAD

**Issue by systemctl603** [CoenraadS/Bracket-Pair-Colorizer-2#363]
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer-2`
- Extension Version: `0.2.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.51.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 43,
		"activateCallTime": 14,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Must invoke loadWASM first."
		}
	]
}
```

**Comment by systemctl603** [comment]
More errors stating this also show up.
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 84,
		"activateCallTime": 38,
		"activateResolvedTime": 1,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "CoenraadS.bracket-pair-colorizer-2",
				"_lower": "coenraads.bracket-pair-colorizer-2"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Must invoke loadWASM first."
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'getRuleStack' of undefined"
		}
	]
}
```

These errors are not consistently showing up, and can typically be solved by a reload, though.

**Comment by ankitbko** [comment]
When starting a debugging session during creation of vscode extension leads to same exception - 

```
stack trace: Error: Must invoke loadWASM first.
	at new u (c:\Users\anksinha\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-oniguruma\release\main.js:1:2639)
	at Object.createOnigString (c:\Users\anksinha\.vscode-insiders\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\textMateLoader.js:53:48)
	at e.createOnigString (c:\Users\anksinha\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:6225)
	at e._tokenize (c:\Users\anksinha\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:8276)
	at e.tokenizeLine2 (c:\Users\anksinha\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:7575)
	at DocumentDecoration.tokenizeLine (c:\Users\anksinha\.vscode-insiders\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:232:55)
	at DocumentDecoration.tokenizeDocument (c:\Users\anksinha\.vscode-insiders\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:116:38)
	at DocumentDecorationManager.updateDocument (c:\Users\anksinha\.vscode-insiders\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:33:32)
	at c:\Users\anksinha\.vscode-insiders\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:94:30
```

**Comment by docwhat** [comment]
Good info. Duplicate of #295

**Comment by aravindvnair99** [comment]
@systemctl603 Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

**Comment by systemctl603** [comment]
> @systemctl603 Please close this as it's a duplicate of #295. Use that thread instead of creating a new one.

Sure.
