### ISSUE TITLE
Extension fails on nixos with an obscure stack

### ISSUE THREAD

**Issue by pshirshov** [CoenraadS/Bracket-Pair-Colorizer-2#451]
```
[2021-09-06 17:03:09.290] [exthost] [error] Activating extension CoenraadS.bracket-pair-colorizer-2 failed due to an error:
[2021-09-06 17:03:09.290] [exthost] [error] Error: Cannot find module '/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/node_modules.asar/vscode-textmate'
Require stack:
- /home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/textMateLoader.js
- /home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/settings.js
- /home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/documentDecorationManager.js
- /home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/extension.js
- /nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/loader.js
- /nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/bootstrap-amd.js
- /nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28190)
    at Function.E._load (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:24778)
    at Function.o._load (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:59872)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/loader.js:4:698)
    at TextMateLoader.getNodeModule (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/textMateLoader.js:107:16)
    at TextMateLoader.loadTextMate (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/textMateLoader.js:110:21)
    at new TextMateLoader (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/textMateLoader.js:19:27)
    at new Settings (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/settings.js:10:31)
    at new DocumentDecorationManager (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/documentDecorationManager.js:9:25)
    at activate (/home/pavel/.vscode/extensions/coenraads.bracket-pair-colorizer-2-0.2.1/out/src/extension.js:7:37)
    at Function._callActivateOptional (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14900)
    at Function._callActivate (/nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:14576)
    at /nix/store/16cn7lg6m81zag6bgv94ckvwdvvcwjp1-vscode-latest/lib/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12779
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

**Comment by Lyndeno** [comment]
I receive the same error. Vscode installed on NixOS, not through home-manager.
